language: generic
sudo: required
install:
  - sudo apt-get -y install rpm createrepo
script: 
  - ./build.sh
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "travis" && ./deploy.sh
env:
  global:
    - secure: XVi/eOSTCYzwB59IATVJoHoh1KomctHAcIE0PXjvypQBRQ5nMY5O53JOGijx9oTiX6wwL3hKZuOcNzO4Ecm4veelra9Yll2/59ax0SCnCnlzP2ld2pu1idVbLxtHvzea87nju36Q71dAOr42mbDwAp7udJsMMo0dUHrbB3YIKiwnzpXqqX4X7gmTOV7OTb3fyMKFSJgaI7KEvxXHd29sNq77FVVWLwiNSI403XHUjserWl0ejsWn4EfgwevfGa3Q2NVSf2IV33iK2LhDx1bJkz0bQcr+b030/ul/DKMpjoRutTopri/u7LB62WvupN32DXWZyzDHk9lMUli14TZeqITuXcHIARt23mtm1xxh2j6VRFcI88ZcD9hwt+9sHtM6XKPB+A1utj5gPku/X+BpOMp/hUUZfXghpt4oS/0JWoeKPnc9TWkdUBVvYk4w4SflmMzkj6I7mGiDVE3nJU2DrjMqd1bF1745brHq9M8kQdP5yhD2QFK3BUuYUnqEAoTdN+F8JMhW64gqt7f81z+45yjzMLAp0q+mlGzj00sV7TTfFxFHAJcLYfTog832w3g8z3zJRvjFyNEdfYZWZBYSIjo4u/CHATs0Eay+P3/XHs3L1iphQS9p46QOA2Myex8jcj2RL6KPs4EbjPWacVe1izBiAWczwjP/NecozLrOABA=
